### ISSUE TITLE
Possible to make an even more fire-and-forget solution?

### ISSUE THREAD

**Issue by jsve** [moritzmhmk/buildroot-camera-rpi#1]
If I use the prebuild release and flash that to the SD. Can I make changes in the configs before flashing, or do I have to make the changes to the files in the ```boot``` partition?

**Comment by moritzmhmk** [comment]
This can be done by either building the project with modified default config files or by [mounting](https://raspberrypi.stackexchange.com/questions/13137/how-can-i-mount-a-raspberry-pi-linux-distro-image) the prebuild image and modifying those files before flashing.
