### ISSUE TITLE
Multiple rpi cameras?

### ISSUE THREAD

**Issue by jstoff** [moritzmhmk/buildroot-camera-rpi#4]
I just got finished building a second rpi camera using this software, but I'm having trouble getting it to show up as a new accessory in the iOS Home app. I modified the name and id in `homebridge-camera-rpi.conf.json ` for both cameras, and both appear to be able to join my network (though both are simply identified as `buildroot`). Am I missing something to get two cameras working in my house?

**Comment by moritzmhmk** [comment]
Make sure to also have a different ``id``.

**Comment by MWDelaney** [comment]
If anyone else comes across this issue, I had to also change the "username" value in `homebridge-camera-rpi.conf.json` or the two cameras conflicted.
