### ISSUE TITLE
buildroot login

### ISSUE THREAD

**Issue by gio-dude** [moritzmhmk/buildroot-camera-rpi#6]
Flashed the latest version to an sd card and on first boot its asking for a buildroot login. What is the login or am I doing something wrong.

**Comment by moritzmhmk** [comment]
There is no need to login.

All configuration can be done on the boot partition of the SD card (see README).

If you want to login for debugging etc. it is "root" with password "toor".

**Comment by gio-dude** [comment]
sorry still a little new to all of this. It makes sense now and worked perfectly. thank you
