### ISSUE TITLE
Camera wont send any footage

### ISSUE THREAD

**Issue by Pairan** [moritzmhmk/buildroot-camera-rpi#9]
Everything works fine, the raspi zero W launches and show up in HomeKit! But when paired, the raspi camera 2.1 wont show any image - "Error loading" is shown in the Homekit display. ("Die Kamera Antwortet nicht")

Any hints on that?

**Comment by moritzmhmk** [comment]
Besides hardware issues (camera not plugged in correctly, cable broken) checking the log could be helpful.

To do so connect a screen and keyboard and log in as user `root` with password `toor` and check the output of `journalctl -fu hap-camera-rpi`.

**Comment by Pairan** [comment]
simple cause: SD-CARD to slow
simple fix: Take a faster SD-Card
